services:
  - type: web
    name: jreports-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
